2023-12-18 10:21:53,679 INFO    MainThread:26520 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-18 10:21:53,679 INFO    MainThread:26520 [wandb_setup.py:_flush():76] Configure stats pid to 26520
2023-12-18 10:21:53,679 INFO    MainThread:26520 [wandb_setup.py:_flush():76] Loading settings from C:\Users\rs1044\.config\wandb\settings
2023-12-18 10:21:53,679 INFO    MainThread:26520 [wandb_setup.py:_flush():76] Loading settings from c:\Users\rs1044\Documents\GitHub\Mixture-of-Experts-based-Federated-Learning-for-Energy-Forecasting\src\time_series\Locallearning\TS_LL_PV_Forecasting_Moe\wandb\settings
2023-12-18 10:21:53,679 INFO    MainThread:26520 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'silent': 'true', 'console': 'off'}
2023-12-18 10:21:53,679 INFO    MainThread:26520 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-18 10:21:53,679 INFO    MainThread:26520 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-18 10:21:53,679 ERROR   MainThread:26520 [wandb_setup.py:_flush():76] [34m[1mwandb[0m: [32m[41mERROR[0m Control-C detected -- Run data was not synced
2023-12-18 10:21:53,679 INFO    MainThread:26520 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\rs1044\Documents\GitHub\Mixture-of-Experts-based-Federated-Learning-for-Energy-Forecasting\src\time_series\Locallearning\TS_LL_PV_Forecasting_Moe\wandb\run-20231218_102153-h2m3cmo6\logs\debug.log
2023-12-18 10:21:53,680 INFO    MainThread:26520 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\rs1044\Documents\GitHub\Mixture-of-Experts-based-Federated-Learning-for-Energy-Forecasting\src\time_series\Locallearning\TS_LL_PV_Forecasting_Moe\wandb\run-20231218_102153-h2m3cmo6\logs\debug-internal.log
2023-12-18 10:21:53,680 INFO    MainThread:26520 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000018005C757D0>
2023-12-18 10:21:53,680 INFO    MainThread:26520 [wandb_init.py:init():564] calling init triggers
2023-12-18 10:21:53,680 INFO    MainThread:26520 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'max_epochs': 100, 'batch_size': 16, 'optimizer': 'Adam', 'learning_rate': 0.001, 'architecture': 'dense_soft_moe'}
2023-12-18 10:21:53,680 INFO    MainThread:26520 [wandb_init.py:init():614] starting backend
2023-12-18 10:21:53,680 INFO    MainThread:26520 [wandb_init.py:init():618] setting up manager
2023-12-18 10:21:53,682 INFO    MainThread:26520 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-12-18 10:21:53,682 INFO    MainThread:26520 [wandb_init.py:init():624] backend started and connected
2023-12-18 10:21:53,686 INFO    MainThread:26520 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-18 10:21:53,686 INFO    MainThread:26520 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-18 10:21:53,686 INFO    MainThread:26520 [wandb_init.py:init():716] updated telemetry
2023-12-18 10:21:53,738 INFO    MainThread:26520 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-18 10:23:24,513 ERROR   MainThread:26520 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-12-18 10:23:24,528 ERROR   MainThread:26520 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\Users\rs1044\Documents\GitHub\Mixture-of-Experts-based-Federated-Learning-for-Energy-Forecasting\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "c:\Users\rs1044\Documents\GitHub\Mixture-of-Experts-based-Federated-Learning-for-Energy-Forecasting\.venv\Lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
